version: "3"

services:
  shopsbot:
    container_name: shopsbot
    image: shopsbot:1.2
    environment:
      TELEGRAM_TOKEN: 'XXXXXXXXXXXXXX_TOKEN_HERE_XXXXXXXXXXXXXXX'
      OUTPUT_FOLDER: '/outputs/'
      REFRESH_MINUTES: '10'
      NEXT_QUERY_SECONDS: '15'
      TZ: 'Europe/Warsaw'
      PYTHONUNBUFFERED: 'true'
      PYTHONIOENCODING: 'UTF-8'
    volumes:
      - './outputs/:/outputs/'
    restart: unless-stopped
